### PR TITLE
correct tab font size when set using global font size setting

### PR DESCRIPTION
**Pull request by drosen0**

### CODE REVIEW

**Comment by oivva** [comment]
Oh, this's a very good set of changes. Thanks a lot! I'll merge it soon. Commit c7d660d has bug with selected sidebar label color, I'll fix it in process of merging.

P.S. For the next commits use this [commit guidelines](https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#commit-message-format) (except the scope notes, we don't need them). I'll improve the docs in the near future.

**Comment by drosen0** [comment]
Oops, my mistake. I only intended the first commit (the tooltip font size fix) to be in this pull request. The others I meant to keep in my own fork, at least for now. I'll resubmit with just the font fix.

**Comment by drosen0** [comment]
Oh, I see that you merged them. Cool. I'll try to follow the guidelines in the future.

**Comment by oivva** [comment]
I have plans to review UI sizes, that's why I don't know if tiny UI will be available in the next release. But   thanks for other changes: 798aaa3, cd282f1 and especially for c7d660d (I forgot about that).

**Comment by drosen0** [comment]
In its current form, I agree 'tiny' isn't ready for release. You're welcome to revert or cherry pick omitting those commits.

**Pull request closed without merging**
